### ISSUE TITLE
Is this meant to be a zephyr module or just an example of how to use NPMX with zephyr? 

### ISSUE THREAD

**Issue by mstumpf585** [NordicSemiconductor/npmx-zephyr#126]
Hello, 

I'm a little confused this repo has a zephyr/module.yml like it is meant to be a module but its CMAKE file under modules seems to have the wrong pathing if you place this repo in the zephyr/modules folder. It will not be able to locate nrfxlib. 

My west.yml looks like this for the npmx-zphyr 

```

    - name: npmx-zephyr
      remote: NordicSemiconductor
      path: modules/npmx-zephyr

```

When you try to build with the following in your west config you get this error output:

```
CMake Error at /workspaces/noctrix-fw-gen2/zephyrproject/modules/npmx-zephyr/modules/CMakeLists.txt:7 (add_subdirectory):
  add_subdirectory given source
  "/workspaces/noctrix-fw-gen2/zephyrproject/modules/npmx-zephyr/../modules/nrfxlib"
  which is not an existing directory.
```

This seems to be because the CMakeLists.txt should actually have 

```
add_subdirectory(${ZEPHYR_CURRENT_MODULE_DIR}/../nrfxlib nrfxlib)
```

alternatively you can change the path to be: 

```
path: npmx-zephyr
```

but that doesn't seem right that it has to be placed outside the modules folder.

**Comment by masz-nordic** [comment]
Hi,
npmx-zephyr is supposed to be an example of npmx integration with an RTOS.
This is a [freestanding application](https://docs.zephyrproject.org/latest/develop/application/index.html#zephyr-freestanding-app) - in pulls in Zephyr, see [west.yml](https://github.com/NordicSemiconductor/npmx-zephyr/blob/main/west.yml#L25-L28).
